dataset:
  data_path: "/scratch_net/biwidl214/ecetin_scratch/data"
  data_device: "cuda"
  images: "images"
  resolution: -1
  eval: true
  white_background: false

  model: latent_hierarchical
  sh_degree: 3
  model_path: ./output/hierarchical_deneme    # ./output/xxxxx
  checkpoint: null
  octree_max_depth: 20
  octree_min_depth: 13

  feat_dim: 32

pipeline:
  convert_SHs_python: false
  compute_cov3D_python: false
  debug: false
  
  use_wandb: false


optimization:
  iterations: 30_000
  test_iterations: [100, 200, 300, 400, 5_000, 10_000, 15_000, 20_000, 25_000, 30_000]
  save_iterations: []
  checkpoint_iterations: [15_000, 30_000]

  random_background: false
  
  densify_until_iter: 15_000
  
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30_000
  
  feature_lr: 0.0025
  opacity_lr: 0.02
  scaling_lr: 0.007
  rotation_lr: 0.002

  mlp_opacity_lr_init: 0.002
  mlp_opacity_lr_final: 0.00002
  mlp_opacity_lr_delay_mult: 0.01
  mlp_opacity_lr_max_steps: 30_000

  mlp_cov_lr_init: 0.004
  mlp_cov_lr_final: 0.004
  mlp_cov_lr_delay_mult: 0.01
  mlp_cov_lr_max_steps: 30_000

  mlp_sh_lr_init: 0.008
  mlp_sh_lr_final: 0.00005
  mlp_sh_lr_delay_mult: 0.01
  mlp_sh_lr_max_steps: 30_000

  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  densification_factor: 0.05
  opacity_reset_interval: 3_000
  opacity_prune_threshold: 0.005
  densify_from_iter: 500
  densify_until_iter: 15_000
  densify_grad_threshold: 0.0002
  random_background: false

  lambda_entropy: 0
  
  freeze_gaussian_geometry: false

  radsplat_prune_threshold: 0.01
  radsplat_prune_at: [16_001, 24_001]